spring:
  profiles:
    active: dev   # 默认使用开发环境

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/gis?useSSL=false&serverTimezone=UTC
    username: gisuser
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect

server:
  port: 8080

jwt:
  secret: "QIHEoEh1hqT2HfbfwbWhbbVIY8ZxYlPRWfNJh7igy6+DymNLYuJFdKe682TkKXLAndqTZJN66JG2tXnQqfbC9CNIJNqxNOWrUjScA66U7RH+UX5sbTTYpnwUkMIQ2OZLB6S04NsRYhVAqWXJakgvW0Qy6q9kPb5Omn/gLvP+bys=""
  expiration: 86400000   # 24小时
